export type ControlTheme = 'ORGANIZATIONAL' | 'PEOPLE' | 'PHYSICAL' | 'TECHNOLOGICAL'

export interface IsoControlDef {
  number: string
  theme: ControlTheme
  title: string
}

export const THEME_LABELS: Record<ControlTheme, string> = {
  ORGANIZATIONAL: '5. Organizacyjne',
  PEOPLE:         '6. Dotyczące ludzi',
  PHYSICAL:       '7. Fizyczne',
  TECHNOLOGICAL:  '8. Technologiczne',
}

export const ISO_CONTROLS: IsoControlDef[] = [
  // 5. Organizational (37)
  { number: '5.1',  theme: 'ORGANIZATIONAL', title: 'Polityki bezpieczeństwa informacji' },
  { number: '5.2',  theme: 'ORGANIZATIONAL', title: 'Role i odpowiedzialności w zakresie bezpieczeństwa informacji' },
  { number: '5.3',  theme: 'ORGANIZATIONAL', title: 'Rozdzielenie obowiązków' },
  { number: '5.4',  theme: 'ORGANIZATIONAL', title: 'Odpowiedzialność kierownictwa' },
  { number: '5.5',  theme: 'ORGANIZATIONAL', title: 'Kontakty z organami władzy' },
  { number: '5.6',  theme: 'ORGANIZATIONAL', title: 'Kontakty z grupami specjalnego zainteresowania' },
  { number: '5.7',  theme: 'ORGANIZATIONAL', title: 'Wywiad o zagrożeniach' },
  { number: '5.8',  theme: 'ORGANIZATIONAL', title: 'Bezpieczeństwo informacji w zarządzaniu projektami' },
  { number: '5.9',  theme: 'ORGANIZATIONAL', title: 'Inwentaryzacja informacji i powiązanych aktywów' },
  { number: '5.10', theme: 'ORGANIZATIONAL', title: 'Dopuszczalne użytkowanie informacji i powiązanych aktywów' },
  { number: '5.11', theme: 'ORGANIZATIONAL', title: 'Zwrot aktywów' },
  { number: '5.12', theme: 'ORGANIZATIONAL', title: 'Klasyfikacja informacji' },
  { number: '5.13', theme: 'ORGANIZATIONAL', title: 'Oznaczanie informacji' },
  { number: '5.14', theme: 'ORGANIZATIONAL', title: 'Transfer informacji' },
  { number: '5.15', theme: 'ORGANIZATIONAL', title: 'Kontrola dostępu' },
  { number: '5.16', theme: 'ORGANIZATIONAL', title: 'Zarządzanie tożsamością' },
  { number: '5.17', theme: 'ORGANIZATIONAL', title: 'Informacje uwierzytelniające' },
  { number: '5.18', theme: 'ORGANIZATIONAL', title: 'Prawa dostępu' },
  { number: '5.19', theme: 'ORGANIZATIONAL', title: 'Bezpieczeństwo informacji w relacjach z dostawcami' },
  { number: '5.20', theme: 'ORGANIZATIONAL', title: 'Bezpieczeństwo informacji w umowach z dostawcami' },
  { number: '5.21', theme: 'ORGANIZATIONAL', title: 'Zarządzanie bezpieczeństwem informacji w łańcuchu dostaw ICT' },
  { number: '5.22', theme: 'ORGANIZATIONAL', title: 'Monitorowanie i zarządzanie zmianami usług dostawców' },
  { number: '5.23', theme: 'ORGANIZATIONAL', title: 'Bezpieczeństwo informacji przy korzystaniu z usług chmurowych' },
  { number: '5.24', theme: 'ORGANIZATIONAL', title: 'Planowanie i przygotowanie zarządzania incydentami bezpieczeństwa' },
  { number: '5.25', theme: 'ORGANIZATIONAL', title: 'Ocena i decyzja dotycząca zdarzeń bezpieczeństwa informacji' },
  { number: '5.26', theme: 'ORGANIZATIONAL', title: 'Reagowanie na incydenty bezpieczeństwa informacji' },
  { number: '5.27', theme: 'ORGANIZATIONAL', title: 'Uczenie się z incydentów bezpieczeństwa informacji' },
  { number: '5.28', theme: 'ORGANIZATIONAL', title: 'Zbieranie dowodów' },
  { number: '5.29', theme: 'ORGANIZATIONAL', title: 'Bezpieczeństwo informacji w trakcie zakłóceń' },
  { number: '5.30', theme: 'ORGANIZATIONAL', title: 'Gotowość ICT dla ciągłości działania' },
  { number: '5.31', theme: 'ORGANIZATIONAL', title: 'Wymagania prawne, ustawowe, regulacyjne i umowne' },
  { number: '5.32', theme: 'ORGANIZATIONAL', title: 'Prawa własności intelektualnej' },
  { number: '5.33', theme: 'ORGANIZATIONAL', title: 'Ochrona dokumentacji' },
  { number: '5.34', theme: 'ORGANIZATIONAL', title: 'Prywatność i ochrona danych osobowych (PII)' },
  { number: '5.35', theme: 'ORGANIZATIONAL', title: 'Niezależny przegląd bezpieczeństwa informacji' },
  { number: '5.36', theme: 'ORGANIZATIONAL', title: 'Zgodność z politykami i standardami bezpieczeństwa informacji' },
  { number: '5.37', theme: 'ORGANIZATIONAL', title: 'Udokumentowane procedury operacyjne' },

  // 6. People (8)
  { number: '6.1', theme: 'PEOPLE', title: 'Weryfikacja przed zatrudnieniem' },
  { number: '6.2', theme: 'PEOPLE', title: 'Warunki zatrudnienia' },
  { number: '6.3', theme: 'PEOPLE', title: 'Świadomość, edukacja i szkolenia z bezpieczeństwa informacji' },
  { number: '6.4', theme: 'PEOPLE', title: 'Postępowanie dyscyplinarne' },
  { number: '6.5', theme: 'PEOPLE', title: 'Odpowiedzialności po zakończeniu lub zmianie zatrudnienia' },
  { number: '6.6', theme: 'PEOPLE', title: 'Umowy o zachowaniu poufności' },
  { number: '6.7', theme: 'PEOPLE', title: 'Praca zdalna' },
  { number: '6.8', theme: 'PEOPLE', title: 'Raportowanie zdarzeń bezpieczeństwa informacji' },

  // 7. Physical (14)
  { number: '7.1',  theme: 'PHYSICAL', title: 'Fizyczny obwód ochronny' },
  { number: '7.2',  theme: 'PHYSICAL', title: 'Fizyczna kontrola dostępu' },
  { number: '7.3',  theme: 'PHYSICAL', title: 'Zabezpieczenie biur, pomieszczeń i obiektów' },
  { number: '7.4',  theme: 'PHYSICAL', title: 'Fizyczne monitorowanie bezpieczeństwa' },
  { number: '7.5',  theme: 'PHYSICAL', title: 'Ochrona przed zagrożeniami fizycznymi i środowiskowymi' },
  { number: '7.6',  theme: 'PHYSICAL', title: 'Praca w strefach bezpiecznych' },
  { number: '7.7',  theme: 'PHYSICAL', title: 'Polityka czystego biurka i czystego ekranu' },
  { number: '7.8',  theme: 'PHYSICAL', title: 'Rozmieszczenie i ochrona urządzeń' },
  { number: '7.9',  theme: 'PHYSICAL', title: 'Bezpieczeństwo aktywów poza siedzibą' },
  { number: '7.10', theme: 'PHYSICAL', title: 'Nośniki danych' },
  { number: '7.11', theme: 'PHYSICAL', title: 'Systemy wspomagające (media wspierające)' },
  { number: '7.12', theme: 'PHYSICAL', title: 'Bezpieczeństwo okablowania' },
  { number: '7.13', theme: 'PHYSICAL', title: 'Konserwacja urządzeń' },
  { number: '7.14', theme: 'PHYSICAL', title: 'Bezpieczne unieszkodliwianie lub ponowne wykorzystanie urządzeń' },

  // 8. Technological (34)
  { number: '8.1',  theme: 'TECHNOLOGICAL', title: 'Urządzenia końcowe użytkowników' },
  { number: '8.2',  theme: 'TECHNOLOGICAL', title: 'Uprzywilejowane prawa dostępu' },
  { number: '8.3',  theme: 'TECHNOLOGICAL', title: 'Ograniczenie dostępu do informacji' },
  { number: '8.4',  theme: 'TECHNOLOGICAL', title: 'Dostęp do kodu źródłowego' },
  { number: '8.5',  theme: 'TECHNOLOGICAL', title: 'Bezpieczne uwierzytelnianie' },
  { number: '8.6',  theme: 'TECHNOLOGICAL', title: 'Zarządzanie pojemnością' },
  { number: '8.7',  theme: 'TECHNOLOGICAL', title: 'Ochrona przed złośliwym oprogramowaniem' },
  { number: '8.8',  theme: 'TECHNOLOGICAL', title: 'Zarządzanie technicznymi podatnościami' },
  { number: '8.9',  theme: 'TECHNOLOGICAL', title: 'Zarządzanie konfiguracją' },
  { number: '8.10', theme: 'TECHNOLOGICAL', title: 'Usuwanie informacji' },
  { number: '8.11', theme: 'TECHNOLOGICAL', title: 'Maskowanie danych' },
  { number: '8.12', theme: 'TECHNOLOGICAL', title: 'Zapobieganie wyciekom danych (DLP)' },
  { number: '8.13', theme: 'TECHNOLOGICAL', title: 'Tworzenie kopii zapasowych informacji' },
  { number: '8.14', theme: 'TECHNOLOGICAL', title: 'Redundancja urządzeń do przetwarzania informacji' },
  { number: '8.15', theme: 'TECHNOLOGICAL', title: 'Logowanie' },
  { number: '8.16', theme: 'TECHNOLOGICAL', title: 'Działania monitorujące' },
  { number: '8.17', theme: 'TECHNOLOGICAL', title: 'Synchronizacja zegarów' },
  { number: '8.18', theme: 'TECHNOLOGICAL', title: 'Stosowanie uprzywilejowanych programów narzędziowych' },
  { number: '8.19', theme: 'TECHNOLOGICAL', title: 'Instalacja oprogramowania w systemach produkcyjnych' },
  { number: '8.20', theme: 'TECHNOLOGICAL', title: 'Bezpieczeństwo sieci' },
  { number: '8.21', theme: 'TECHNOLOGICAL', title: 'Bezpieczeństwo usług sieciowych' },
  { number: '8.22', theme: 'TECHNOLOGICAL', title: 'Segregacja sieci' },
  { number: '8.23', theme: 'TECHNOLOGICAL', title: 'Filtrowanie stron internetowych' },
  { number: '8.24', theme: 'TECHNOLOGICAL', title: 'Stosowanie kryptografii' },
  { number: '8.25', theme: 'TECHNOLOGICAL', title: 'Bezpieczny cykl wytwarzania oprogramowania' },
  { number: '8.26', theme: 'TECHNOLOGICAL', title: 'Wymagania bezpieczeństwa aplikacji' },
  { number: '8.27', theme: 'TECHNOLOGICAL', title: 'Bezpieczna architektura i zasady inżynierii systemów' },
  { number: '8.28', theme: 'TECHNOLOGICAL', title: 'Bezpieczne kodowanie' },
  { number: '8.29', theme: 'TECHNOLOGICAL', title: 'Testowanie bezpieczeństwa w procesie wytwarzania' },
  { number: '8.30', theme: 'TECHNOLOGICAL', title: 'Wytwarzanie oprogramowania zleconego na zewnątrz' },
  { number: '8.31', theme: 'TECHNOLOGICAL', title: 'Separacja środowisk wytwórczego, testowego i produkcyjnego' },
  { number: '8.32', theme: 'TECHNOLOGICAL', title: 'Zarządzanie zmianami' },
  { number: '8.33', theme: 'TECHNOLOGICAL', title: 'Informacje testowe' },
  { number: '8.34', theme: 'TECHNOLOGICAL', title: 'Ochrona systemów informatycznych podczas audytów' },
]
